---
title: "Summary Code"
author: Finn
output:
  html_document:
    toc: yes
    number_section: yes
    fig_caption: true
  pdf_document:
    toc: yes
  always_allow_html: true
date: "`r format(Sys.time(), '%d %B %Y')`"
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.align = 'center', echo = TRUE)
```

```{r libs, include = FALSE}
library(tidyverse)
library(data.table)
library(leaflet)
library(ggplot2)
library(RColorBrewer) #display.brewer.all()
library(colorRamps)
library(cowplot)
library(uwot)
library(leaflet.extras)
library(sp)
library(htmltools)
library(stringr)
library(patchwork)
library(readr)
library(knitr)
library(ggeffects)
#library(parasiteLoad)

SOTA <- read.csv("https://raw.githubusercontent.com/derele/Mouse_Eimeria_Field/master/data_products/SOTA_Data_Product.csv")

# Load Palette ####
r <- c(  0,  64, 128, 179, 217, 255)
g <- c(  0,  12,  25,  25,  12,   0)
b <- c(255, 249, 243, 191,  95,   0)
  
beach <- function (n, name = c("beach.colors")) 
  {
    beach.colors = rgb(r,g,b,maxColorValue = 255)
    name = match.arg(name)
    orig = eval(parse(text = name))
    rgb = t(col2rgb(orig))
    temp = matrix(NA, ncol = 3, nrow = n)
    x = seq(0, 1, , length(orig))
    xg = seq(0, 1, , n)
    for (k in 1:3) {
      hold = spline(x, rgb[, k], n = n)$y
      hold[hold < 0] = 0
      hold[hold > 255] = 255
      temp[, k] = round(hold)
    }
    palette = rgb(temp[, 1], temp[, 2], temp[, 3], maxColorValue = 255)
    palette
  }
```

# qPCR Results
```{r qPCR results, echo = F}
Crypto_Detection <- read.csv("https://raw.githubusercontent.com/derele/Mouse_Eimeria_Field/master/data_products/Crypto_Detection.csv")

All_Pos <- Crypto_Detection %>% 
  filter(ILWE_Crypto_Ct > 0) %>%
  arrange(desc(Oocyst_Predict_Crypto)) %>%
  mutate(id = row_number()) %>%
  select(id, Mouse_ID, ILWE_Crypto_Ct, Oocyst_Predict_Crypto, Latitude, Longitude, HI)

kable(All_Pos,
      col.names = c("", "Mouse_ID", "ILWE_Crypto_Ct", "Oocyst_Predict_Crypto", "Latitude", "Longitude", "HI"),
      align = "ccc",
      caption = "Table 1: All _Cryptosporidium_-positive samples, arranged by Ct_mean")


Western_Pos <- Crypto_Detection %>% 
  filter(ILWE_Crypto_Ct > 0,
         HI <= 0.5) %>%
  arrange(desc(Oocyst_Predict_Crypto)) %>%
  mutate(id = row_number()) %>%
  select(id, Mouse_ID, ILWE_Crypto_Ct, Oocyst_Predict_Crypto, Latitude, Longitude, HI)

kable(Western_Pos,
      col.names = c("", "Mouse_ID", "ILWE_Crypto_Ct", "Oocyst_Predict_Crypto", "Latitude", "Longitude", "HI"),
      align = "ccc",
      caption = "Table 2: Western _Cryptosporidium_-positive samples, arranged by Ct_mean")

Eastern_Pos <- Crypto_Detection %>% 
  filter(ILWE_Crypto_Ct > 0, HI > 0.5) %>%
  arrange(desc(Oocyst_Predict_Crypto)) %>%
  mutate(id = row_number()) %>%
  select(id, Mouse_ID, ILWE_Crypto_Ct, Oocyst_Predict_Crypto, Latitude, Longitude, HI)

kable(Eastern_Pos,
      col.names = c("", "Mouse_ID", "ILWE_Crypto_Ct", "Oocyst_Predict_Crypto", "Latitude", "Longitude", "HI"),
      align = "ccc",
      caption = "Table 3: Eastern _Cryptosporidium_-positive samples, arranged by Ct_mean")
```





```{r OP_Model, echo = F}
Standard_Curve <- read.csv("https://raw.githubusercontent.com/derele/Mouse_Eimeria_Field/master/data_input/Cryptosporidium/Crypto_Standard_Curve.csv")
colnames(Standard_Curve)[colnames(Standard_Curve)%in%"Ct_mean"] <- "ILWE_Crypto_Ct"


Standard_Curve     <-  filter(Standard_Curve, ILWE_Crypto_Ct > 0)
linear_model0     <- lm(log2(Amount_Oocysts) ~ ILWE_Crypto_Ct, data = Standard_Curve)
Oocyst_Predict_Crypto    <- 2^predict(linear_model0, newdata = Crypto_Detection)
Crypto_qPCR <- data.frame(Crypto_Detection, Oocyst_Predict_Crypto)
Crypto_qPCR <- Crypto_qPCR %>% mutate(Oocyst_Predict_Crypto = replace(Oocyst_Predict_Crypto, Oocyst_Predict_Crypto == "4292821751815.77", "0"))
Crypto_qPCR$Oocyst_Predict_Crypto <- as.integer(Crypto_qPCR$Oocyst_Predict_Crypto)
```


# Hybrid Index

```{r mini map HI , echo = F, message = F, warning = F}
SOTA <- read.csv("https://raw.githubusercontent.com/derele/Mouse_Eimeria_Field/master/data_products/SOTA_Data_Product.csv")%>% filter(!is.na(Latitude), !is.na(Longitude), !is.na(HI), Mouse_ID != "SK_2697")
#SOTA <- SOTA[SOTA$Mouse_ID %like% "AA_", ]


Crypto_Detection_tested <- read.csv("https://raw.githubusercontent.com/derele/Mouse_Eimeria_Field/master/data_products/Crypto_Detection.csv") %>% filter(ILWE_Crypto_Ct >= 0, !is.na(Latitude), !is.na(Longitude), !is.na(HI))
Crypto_Detection <- read.csv("https://raw.githubusercontent.com/derele/Mouse_Eimeria_Field/master/data_products/Crypto_Detection.csv") %>% filter(ILWE_Crypto_Ct > 0, !is.na(Latitude), !is.na(Longitude), !is.na(HI))
Crypto_Detection_21 <- read.csv("https://raw.githubusercontent.com/derele/Mouse_Eimeria_Field/master/data_products/Crypto_Detection.csv") %>% filter(Year == 2021, ILWE_Crypto_Ct > 0, !is.na(Latitude), !is.na(Longitude))

map <- Crypto_Detection_21 %>% leaflet() %>% addProviderTiles("CartoDB") %>% setView(lat = 52.520007, lng =13.404954, zoom = 8)

# Cutting
SOTA$HI <- as.numeric(SOTA$HI)
SOTA$HI_Level <-  cut(SOTA$HI, c(0, 0.001, 0.250, 0.500, 0.750, 0.999, 1), include.lowest = T , labels = c('HI = 0', 'HI < 0.25', 'HI < 0.5', 'HI < 0.75', 'HI < 1', 'HI = 1'))
Crypto_Detection_21$Ct_Level <- cut(Crypto_Detection_21$ILWE_Crypto_Ct, c(1, 28, 30, 32, 34, 36, 40), include.lowest = F , labels = c(' < 28  ', '28 - 30', '30 - 32', '32 - 34', '34 - 36', ' > 36'))

data_col_HI           = colorFactor(beach(6), SOTA$HI)
data_col_HI_Level     = colorFactor(beach(6), SOTA$HI_Level)
data_col_Ct_Level     = colorFactor(brewer.pal(4, "YlOrRd"), Crypto_Detection_21$Ct_Level, reverse = T)
data_col_Eim_Infected = colorFactor(brewer.pal(3, "YlOrRd"), SOTA$Eimeria_Positive)


Ct_bl_30     <- Crypto_Detection_21 %>% filter(ILWE_Crypto_Ct <= 30 & ILWE_Crypto_Ct > 0)
Ct_bl_34     <- Crypto_Detection_21 %>% filter(ILWE_Crypto_Ct <= 34 & ILWE_Crypto_Ct > 30)
Ct_bl_36     <- Crypto_Detection_21 %>% filter(ILWE_Crypto_Ct <= 36 & ILWE_Crypto_Ct > 34)
Ct_over_36   <- Crypto_Detection_21 %>% filter(ILWE_Crypto_Ct > 36)
SOTA         <- SOTA %>% filter(!is.na(HI))


map %>%
  addPolylines(lat = c(55.0000, 53.6000, 53.51885, 52.8875  , 52.6053, 51.8978, 45.0000), lng = c(10.0000, 11.4563, 12.4464,13.8119 , 13.8756, 13.8103, 13.5000), color = "purple", weight = 55, opacity = 0.1) %>%
  addCircleMarkers(data = SOTA,
                   col = ~data_col_HI(HI),
                   label = ~htmlEscape(Mouse_ID),
                   popup = ~paste("<b>Mouse_ID:<b>",as.character(Mouse_ID), "<br>",
                                  "<b>Location:<b>", as.character(Latitude), "<b>,<b>", as.character(Longitude), "<br>",
                                  "<b>HI:<b>",      as.character(HI), "<br>",
                                  "<b>Year:<b>",    as.character(Year),"<br>",
                                  "<b>Ct:<b>",      as.character(ILWE_Crypto_Ct),"<br>",
                                  "<b>Oocysts:<b>", as.character(Oocyst_Predict_Crypto), "<br>",
                                  "<b>Sex:<b>", Sex, "<br>",
                                  sep=" "),
                   opacity = 1,
                   radius = 3,
                   group = "Samples (total)") %>%
  addCircleMarkers(data = Crypto_Detection_tested,
                   col = ~data_col_HI(HI),
                   label = ~htmlEscape(Mouse_ID),
                   popup = ~paste("<b>Mouse_ID:<b>",as.character(Mouse_ID), "<br>",
                                  "<b>Location:<b>", as.character(Latitude), "<b>,<b>", as.character(Longitude), "<br>",
                                  "<b>HI:<b>",      as.character(HI), "<br>",
                                  "<b>Year:<b>",    as.character(Year),"<br>",
                                  "<b>Ct:<b>",      as.character(ILWE_Crypto_Ct),"<br>",
                                  "<b>Oocysts:<b>", as.character(Oocyst_Predict_Crypto), "<br>",
                                  "<b>Sex:<b>", Sex, "<br>",
                                  sep=" "),
                   opacity = 1,
                   radius = 3,
                   group = "Samples (Crypto-tested)") %>%
  addCircleMarkers(data = Crypto_Detection,
                   col = ~data_col_HI(HI),
                   label = ~htmlEscape(Mouse_ID),
                   popup = ~paste("<b>Mouse_ID:<b>",as.character(Mouse_ID), "<br>",
                                  "<b>Location:<b>", as.character(Latitude), "<b>,<b>", as.character(Longitude), "<br>",
                                  "<b>HI:<b>",      as.character(HI), "<br>",
                                  "<b>Year:<b>",    as.character(Year),"<br>",
                                  "<b>Ct:<b>",      as.character(ILWE_Crypto_Ct),"<br>",
                                  "<b>Oocysts:<b>", as.character(Oocyst_Predict_Crypto), "<br>",
                                  "<b>Sex:<b>", Sex, "<br>",
                                  sep=" "),
                   opacity = 1,
                   radius = 3,
                   group = "Samples (Crypto-positive)") %>%

  addLegend("bottomleft", 
            pal = data_col_HI_Level, 
            title = "HI",
            values = SOTA$HI_Level, 
            group = c('HI = 0', 'HI < 0.25', 'HI < 0.5', 'HI < 0.75', 'HI < 1', 'HI = 1'),
            opacity = 1) %>%
addLayersControl(baseGroups = c("Samples (total)", "Samples (Crypto-tested)", "Samples (Crypto-positive)"), 
                 options = layersControlOptions(collapsed = F))

```